package ipleiria.pdm.homecoffee.Enums;

public enum FragmentsEnum {
    HOME_FRAGMENT,
    GALLERY_FRAGMENT,
    SLIDES_HOW_FRAGMENT,
    DEVICES_FRAGMENT,
    ADD_DEVICES_FRAGMENT,
    ADD_ROOM_FRAGMENT,
    ADD_DEVICES_SELECT_ROOM_FRAGMENT,
    DEVICE_DETAILS_FRAGMENT,
    ADD_DEVICES_SELECT_SENSOR_FRAGMENT,
    EDIT_DEVICES_SELECT_ROOM_FRAGMENT
}
